### ISSUE TITLE
Profile popup is blocked too

### ISSUE THREAD

**Issue by pamtbaau** [MaySoMusician/breakthrough-twitter-login-wall#1]
I would like to thank you for this plugin to bypass the annoying Twitter popup to login. Thanks!

Also a feature request.  The plugin also blocks a popup when hovering a users image/avatar. It would be nice if login popups are being blocked and profile popups are being allowed.

**Comment by MaySoMusician** [comment]
@pamtbaau Thank you for using the extension and getting in touch with me!
And I recognize a popup of the profile icon being hidden unexpectedly. I will fix this bug soon.

**Comment by pamtbaau** [comment]
Glad you can reproduce, however...

For some reason, popups appearing after hovering a profile's image/avatar are not being blocked anymore... Maybe a change in Twitters HTML tree?

**Comment by MaySoMusician** [comment]
@pamtbaau Yeah I have changed some logic to find the div element we should hide, when upgrading to v1.x, so the popups of the user may no longer be hidden in the latest version.

By the way, however, some element that should not be hidden may be unfortunately still got hidden at this time (e.g. full-screen profile icon dialog when you click someone's icon in their profile page). I will continue to deal with them!

**Comment by pamtbaau** [comment]
Great! And thank you.
