### ISSUE TITLE
mobile.twitter.com too

### ISSUE THREAD

**Issue by jimdigriz** [MaySoMusician/breakthrough-twitter-login-wall#4]
Can you also include `://mobile.twitter.com` too?

I get sent a lot of links by people on mobile devices and Twitter does not redirect desktop traffic to their non-mobile URL so the extension never engages.

**Comment by MaySoMusician** [comment]
@jimdigriz, and all the others who suggest this: thanks for your suggestion, and I'm so sorry for my late response! I'm making soon the extension working on mobile website as well.
