### ISSUE TITLE
Use a MutationObserver to prevent removal delay

### ISSUE THREAD

**Issue by Alainx277** [MaySoMusician/breakthrough-twitter-login-wall#5]
Currently, the page is checked for a login popup every second. This makes the site usable at all, which is great.
Unfortunately, the popup is still shown for a max of one second, which is distracting.

I propose to use a `MutationObserver` to be notified of added elements, and check if they are a popup. This way, the login popup can be removed before even being shown to the user.

**Comment by ghost** [comment]
I too am waiting for this fix.

**Comment by MaySoMusician** [comment]
@Alainx277 @nymbee16 
Thanks for pointing out. Actually I knew there is a `MutationObserver`, but that was in my skill slightly difficult to publish the extension hastily. Now I'm allowed to spend so more time to develop than at that time that I can try to utilize `MutationObserver`s to remove modals.
